version: '3.5'

services:
  app:
    build: .
    container_name: finreach-container
    working_dir: /usr/src/app
    environment:
      APP_ENVIRONMENT_NAME: development
    volumes:
      - '.:/usr/src/app'
      - finreach-usrlocal:/usr/local/

volumes:
  finreach-usrlocal:

networks:
  local:

